export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAIL = 'ADD_CATEGORY_FAIL';

export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAIL = 'UPDATE_CATEGORY_FAIL';

export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL';

export const GET_CATEGORIES_WITH_PRODUCTS = 'GET_CATEGORIES_WITH_PRODUCTS';
export const GET_CATEGORIES_WITH_PRODUCTS_SUCCESS = 'GET_CATEGORIES_WITH_PRODUCTS_SUCCESS';
export const GET_CATEGORIES_WITH_PRODUCTS_FAIL = 'GET_CATEGORIES_WITH_PRODUCTS_FAIL';

export const GET_PRODUCT_INFORMATION = 'GET_PRODUCT_INFORMATION';
export const GET_PRODUCT_INFORMATION_SUCCESS = 'GET_PRODUCT_INFORMATION_SUCCESS';
export const GET_PRODUCT_INFORMATION_FAIL = 'GET_PRODUCT_INFORMATION_FAIL';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL';

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';

export const ADD_VARIATION = 'ADD_VARIATION';
export const ADD_VARIATION_SUCCESS = 'ADD_VARIATION_SUCCESS';
export const ADD_VARIATION_FAIL = 'ADD_VARIATION_FAIL';

export const UPDATE_VARIATION = 'UPDATE_VARIATION';
export const UPDATE_VARIATION_SUCCESS = 'UPDATE_VARIATION_SUCCESS';
export const UPDATE_VARIATION_FAIL = 'UPDATE_VARIATION_FAIL';

export const DELETE_VARIATION = 'DELETE_VARIATION';
export const DELETE_VARIATION_SUCCESS = 'DELETE_VARIATION_SUCCESS';
export const DELETE_VARIATION_FAIL = 'DELETE_VARIATION_FAIL';

export const GET_PROFILE_BY_TOKEN = 'GET_PROFILE_BY_TOKEN';
export const GET_PROFILE_BY_TOKEN_SUCCESS = 'GET_PROFILE_BY_TOKEN_SUCCESS';
export const GET_PROFILE_BY_TOKEN_FAIL = 'GET_PROFILE_BY_TOKEN_FAIL';

export const SET_TOKEN = 'SET_TOKEN';

export const GET_STORE_INFO = 'GET_STORE_INFO';
export const GET_STORE_INFO_SUCCESS = 'GET_STORE_INFO_SUCCESS';
export const GET_STORE_INFO_FAIL = 'GET_STORE_INFO_FAIL';

export const GET_SUMMARIES = 'GET_SUMMARIES';
export const GET_SUMMARIES_SUCCESS = 'GET_SUMMARIES_SUCCESS';
export const GET_SUMMARIES_FAIL = 'GET_SUMMARIES_FAIL';

export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAIL = 'GET_ORDERS_FAIL';

export const GET_ACTIVE_ORDERS = 'GET_ACTIVE_ORDERS';
export const GET_ACTIVE_ORDERS_SUCCESS = 'GET_ACTIVE_ORDERS_SUCCESS';
export const GET_ACTIVE_ORDERS_FAIL = 'GET_ACTIVE_ORDERS_FAIL';

export const GET_ORDER_INFORMATION = 'GET_ORDER_INFORMATION';
export const GET_ORDER_INFORMATION_SUCCESS = 'GET_ORDER_INFORMATION_SUCCESS';
export const GET_ORDER_INFORMATION_FAIL = 'GET_ORDER_INFORMATION_FAIL';

